services:
  jobmanager:
    build:
      context: ./
    container_name: flink_jobmanager
    hostname: jobmanager
    command: jobmanager
    ports:
      - "8081:8081"  # Flink Web UI
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - flink_network
    volumes:
      - ./job:/opt/flink/job  # Mount your job scripts into the container
      - ./config:/opt/flink/conf  # Mount Flink configuration
      - ./lib:/opt/flink/lib  # Mount Kafka JARs
      - ./logs:/opt/flink/log  # Persist logs

  taskmanager:
    build:
      context: ./
    container_name: flink_taskmanager
    hostname: taskmanager
    command: taskmanager
    depends_on:
      - jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - flink_network
    volumes:
      - ./config:/opt/flink/conf  # Mount Flink configuration
      - ./lib:/opt/flink/lib  # Mount Kafka JARs
      - ./logs:/opt/flink/log  # Persist logs

networks:
  flink_network:
    driver: bridge
