name: Continuous Integration

on:
  push:
    branches:
      - dev
      - stage
      - main
  pull_request:
    branches:
      - dev
      - stage
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Install dependencies for all components
      - name: Install dependencies
        run: |
          for req in $(find . -name 'requirements.txt'); do
            echo "Installing dependencies from $req"
            pip install -r $req
          done

      # Debug Python Version
      - name: Debug Python Version
        run: |
          python --version
          pip --version

      # Debug environment variables
      - name: Debug environment variables
        run: |
          echo "CONFLUENT_STAGE_KEY=${CONFLUENT_STAGE_KEY:-not set}"
          echo "CONFLUENT_STAGE_SECRET=${CONFLUENT_STAGE_SECRET:-not set}"
          echo "KAFKA_BROKER=${KAFKA_BROKER:-not set}"
        env:
          CONFLUENT_STAGE_KEY: ${{ secrets.CONFLUENT_STAGE_KEY }}
          CONFLUENT_STAGE_SECRET: ${{ secrets.CONFLUENT_STAGE_SECRET }}
          KAFKA_BROKER: ${{ secrets.KAFKA_BROKER }}

      # Run all tests
      - name: Run tests
        env:
          CONFLUENT_STAGE_KEY: ${{ secrets.CONFLUENT_STAGE_KEY }}
          CONFLUENT_STAGE_SECRET: ${{ secrets.CONFLUENT_STAGE_SECRET }}
          KAFKA_BROKER: ${{ secrets.KAFKA_BROKER }}
        run: |
          for dir in $(find . -name 'tests' -type d); do
            echo "Running tests in $dir"
            pytest $dir
          done

      # Lint the code
      - name: Lint code
        run: flake8 .
