name: Continuous Integration

on:
  push:
    branches:
      - dev
      - stage
      - main
  pull_request:
    branches:
      - dev
      - stage
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"  # Downgrade Python version

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Install Docker-Compose
      - name: Install Docker-Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose --version

      # Start Kafka with Docker Compose
      - name: Start Kafka
        working-directory: ./kafka  # Change to your Kafka Docker Compose folder
        run: |
          docker-compose up -d
          docker-compose ps

      # Wait for Kafka to be ready
      - name: Wait for Kafka to be ready
        run: |
          echo "Waiting for Kafka to be ready..."
          for i in {1..30}; do
            if echo dump | nc localhost 9092 &>/dev/null; then
              echo "Kafka is ready!"
              break
            fi
            echo "Waiting for Kafka..."
            sleep 2
          done

      # Install dependencies for all components
      - name: Install dependencies
        run: |
          for req in $(find . -name 'requirements.txt'); do
            echo "Installing dependencies from $req"
            pip install -r $req
          done

      # Debug Python Version
      - name: Debug Python Version
        run: |
          python --version
          pip --version

      # Debug environment variables
      - name: Debug environment variables
        run: |
          echo "CONFLUENT_STAGE_KEY=${CONFLUENT_STAGE_KEY:-not set}"
          echo "CONFLUENT_STAGE_SECRET=${CONFLUENT_STAGE_SECRET:-not set}"
          echo "KAFKA_BROKER=${KAFKA_BROKER:-not set}"
        env:
          CONFLUENT_STAGE_KEY: ${{ secrets.CONFLUENT_STAGE_KEY }}
          CONFLUENT_STAGE_SECRET: ${{ secrets.CONFLUENT_STAGE_SECRET }}
          KAFKA_BROKER: localhost:9092  # Update to your Kafka broker URL

      # Run all tests
      - name: Run tests
        env:
          CONFLUENT_STAGE_KEY: ${{ secrets.CONFLUENT_STAGE_KEY }}
          CONFLUENT_STAGE_SECRET: ${{ secrets.CONFLUENT_STAGE_SECRET }}
          KAFKA_BROKER: localhost:9092  # Update to your Kafka broker URL
        run: |
          for dir in $(find . -name 'tests' -type d); do
            echo "Running tests in $dir"
            pytest $dir
          done

      # Lint the code
      - name: Lint code
        run: flake8 .

      # Stop Kafka
      - name: Stop Kafka
        working-directory: ./kafka  # Change to your Kafka Docker Compose folder
        run: docker-compose down
