name: Continuous Integration

on:
  push:
    branches:
      - dev
      - stage
      - main
  pull_request:
    branches:
      - dev
      - stage
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Debug Python Version
      - name: Debug Python Version
        run: |
          python --version
          pip --version

      # Install dependencies for all components
      - name: Install dependencies
        run: |
          for req in $(find . -name 'requirements.txt'); do
            echo "Installing dependencies from $req"
            pip install -r $req
          done

      # Install flake8 explicitly
      - name: Install flake8
        run: pip install flake8

      # ADD Run all tests


      # ADD Lint the code

