name: Deploy to Staging

on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker images
        run: |
          docker build -f Dockerfile -t myapp-fastapi:stage ./fastapi

      - name: Deploy to Staging
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.override.stage.yml up -d
